### PR TITLE
Added an option in config.json that stops the bot from resetting its skin combo when a new player joins.

### PR DESCRIPTION
**Pull request by BigBrain21**
A lot of people have been requesting this so I made it so you can choose to make the bot not reset each time a new player joins, but it will still reset when it is invited to a new party.

### CODE REVIEW

**Comment by xMistt** [comment]
What if the bot is joined?

**Comment by BigBrain21** [comment]
If it gets joined then it is a default skin I will fix that

**Comment by xMistt** [comment]
That wont work.

**Comment by xMistt** [comment]
It changes skin on start up, what if the bot is then kicked from a party?

**Pull request closed without merging**
