### PR TITLE
Change JSON config to YAML

### PR DESCRIPTION
**Pull request by andre4ik3**
JSON confuses a lot of people. YAML would be better, since it doesn't require strict quotes, and is overall easier to read than JSON. 

I have also included an automatic conversion from the JSON config to YAML config, with backups, an updated sample config file, and included pyyaml in requirements.

### CODE REVIEW

**Comment by Tommy3344** [comment]
no

**Comment by andre4ik3** [comment]
yes

**Comment by Tommy3344** [comment]
json is just better

**Comment by i386wim** [comment]
No, YAML Is just way better

**Comment by xMistt** [comment]
I don't see any major improvements to move from JSON to YAML after so long.

**Comment by andre4ik3** [comment]
._. ok

**Comment by xMistt** [comment]
I appreciate the pr and don't hesitate to make them in the future but currently, I don't see any reason in accepting this.

**Pull request closed without merging**
