### PR TITLE
Added shouts

### PR DESCRIPTION
**Pull request by realkyro**

### CODE REVIEW

**Comment by SWEATYRAIDEN** [comment]
I can't make a lobby not plzzzzzzz help bro

**Comment by SWEATYRAIDEN** [comment]
So can U make me one thnx

**Comment by SWEATYRAIDEN** [comment]
So can U make me one thnx

**Comment by realkyro** [comment]
you can boost the discord server to get a bot

**Comment by matisseke** [comment]
HOW CAN I FIX:  [PartyBot] [21:23:25] [ERROR] Could not authenticate. Error: 'code'

**Comment by matisseke** [comment]
Schermopname (52)

**Comment by soyDonatello** [comment]
helppp

**Comment by soyDonatello** [comment]
did you fixed it

**Comment by soyDonatello** [comment]
Why did you @Luuzy muted me? I did post in correct channels.

**Comment by soyDonatello** [comment]
I was searching for help :/

**Comment by soyDonatello** [comment]
Yeah, im noob in discord, i tought i could @ all. I was searching for help

**Comment by soyDonatello** [comment]
[PartyBot] [21:05:36] [ERROR] Could not authenticate. Error: 'code'

**Comment by realkyro** [comment]
stop making comments on my closed pull request

**Comment by realkyro** [comment]
It has nothing to do with it

**Pull request closed without merging**
