### PR TITLE
Add run on repl.it badge to README

### PR DESCRIPTION
**Pull request by XanOnGH**
This pull request adds a  badge to the . This will allow users to easily run this repository in their browser, without having to set up an environment. You can learn more about Repl.it [here](https://repl.it).

### CODE REVIEW

**Comment by wavy0** [comment]
y

**Comment by Miguelin-code** [comment]
Hi

**Comment by wavy0** [comment]
uhh yeah why are there 2 run on repl.it badge to readme pull requests

**Comment by kaaax0815** [comment]
There wont be an pull, because https://partybot.net/ is based on https://github.com/PirxcyFinal/PartyBotBackup

**Review by aboodyjameel — COMMENTED** [review]
Hi

**Pull request closed without merging**
